apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events-external-py
  name: events-external-py
spec:
  replicas: 3
  selector:
    matchLabels:
      app: events-external-py
  strategy: {}
  template:
    metadata:
      labels:
        app: events-external-py
    spec:
      containers:
      - image: akarnam/python_app:v0.1
        name: events-external-py
        imagePullPolicy: "Always"
        env:
        - name: SERVER
          value: "http://events-internal"
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.2"
status: {}